config/routes.rb
Promosacian::Application.routes.draw do
  devise_for :admins, :path => "admins", :path_names => { :sign_in => 'ingresar', :sign_out => 'salir', :password => 'secreto', :confirmation => 'verificacion', :unlock => 'desbloquear', :registration => 'registro', :sign_up => 'inscribirse' }
  authenticated :admin do
    root :to => 'contactos#index'
  end

  resources :contactos

  match 'terminos' => 'contactos#terminos'

  root :to => 'contactos#new'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/contacto.rb
# coding: utf-8
class Contacto < ActiveRecord::Base
  attr_accessible :email, :nombre, :telefono, :pais

  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i

  PAISES = [["Perú", "pe"],
            ["Bolivia", "bo"],
            ["Costa Rica", "cr"]]

  validates :email, :nombre, :telefono, :presence => true
  validates :email, :telefono, :uniqueness => true
  validates :nombre, :length => { :maximum => 200 }
  validates :telefono, :length => { :maximum => 20 }
  validates :email, :length => { :maximum => 100 },
    :format => EMAIL_REGEX

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |contacto|
        csv << contacto.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contactos_controller.rb
# coding: utf-8
class ContactosController < InheritedResources::Base
  actions :all, :except => [ :show, :edit, :update]
  before_filter :authenticate_admin!, :except => [:terminos, :new, :create]

  before_filter :detect_pais

  def detect_pais
    @country_code = request.location.country_code
    case @country_code
    when "PE"
      @pais = 'Perú'
    when "BO"
      @pais = 'Bolivia'
    when "CR"
      @pais = 'Costa Rica'
    else
      @pais = 'Perú'
    end
  end

  def index
    @contactos = Contacto.order(:created_at).reverse_order.paginate(:page => params[:page], :per_page => 100)

    filename = "contactos_sacian_" + Date.today.strftime("%b%m%Y").gsub(/[^0-9a-z]/, "_") + ".csv"

    respond_to do |format|
      format.html
      format.csv { send_data @contactos.to_csv, :type => 'text/csv; charset=utf-8; header=present',
      :filename => filename }
    end

  end

  def create
    @contacto = Contacto.new(params[:contacto])
    create! do |success, failure|
      success.html do
        case @contacto.pais
        when 'bo'
          ContactosMailer.contact_registration_bo(@contacto).deliver
          ContactosMailer.contact_confirmation_bo(@contacto).deliver
        when 'pe'
          ContactosMailer.contact_registration_pe(@contacto).deliver
          ContactosMailer.contact_confirmation_pe(@contacto).deliver
        when 'cr'
          ContactosMailer.contact_registration_cr(@contacto).deliver
          ContactosMailer.contact_confirmation_cr(@contacto).deliver
        end

        flash[:notice] = "Gracias por participar, pronto nos estaremos comunicando contigo para programar la consulta."
        redirect_to root_path
      end

      failure.html do
        flash[:notice] = "No se envió el mensaje, corrige los campos y vuelve a intentar."
        render :action => "new"
      end

    end
  end

  def terminos

  end

  protected
    def collection
      @contactos ||= end_of_association_chain.paginate(:page => params[:page], :per_page => 1)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/views/admins/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/contactos/_form.html.haml
%h1 "Prueba y Comprueba"
%h2 Prueba nuestro nuevo producto "Sacian" y comprueba que Lain sí funciona.

%section#content{:role => 'main'}
  = image_tag 'sacian.png', id: 'sacian'

  = form_for @contacto do |f|
    #sello
      = image_tag 'sello.png'
    %legend
      Completa tus datos, prueba Sacián de regalo, obtén
      %br
      una consulta de evaluación gratis y empieza ahora
      %br
      mismo a cambiar tu vida.
    - if @contacto.errors.any?
      :javascript
        document.getElementById('notice').style.background = 'red'
      #error_explanation
        %h2= "#{pluralize(@contacto.errors.count, "error")} en el formulario"
        %ul
          - @contacto.errors.full_messages.each do |msg|
            %li= msg

    .field
      = f.label :nombre
      = f.text_field :nombre
    .field
      = f.label :telefono
      = f.text_field :telefono
    .field
      = f.label :email
      = f.text_field :email
    .field
      = f.label :pais
      = f.select :pais, options_for_select(Contacto::PAISES, :selected => @country_code)
    .actions
      = f.submit 'Save'

  Sacian forma parte del tratamiento exclusivo de LAIN

%footer
  %p#bases
    = link_to 'Ver bases y condiciones.', terminos_path, target: '_blank'
    %br
    Promoción válida por este mes.
  = link_to image_tag('lain.png'), 'http://www.lainadelgaza.net', target: '_blank', id: 'lain'

app/views/contactos/index.html.haml
.container
  %h1 Listado de contactos SACIAN
  
  = link_to 'Descargar en formato Excel', contactos_path(format: :csv), :class => 'btn btn-primary'
  = link_to 'Salir', destroy_admin_session_path, :method => :delete, :class => 'btn btn-primary'
  
  %br
  
  %table.table.table-striped
    %thead
      %tr
        %th Nombre
        %th Telefono
        %th Email
        %th País
        %th Fecha
        %th
  
    - @contactos.each do |contacto|
      %tr
        %td= contacto.nombre
        %td= contacto.telefono
        %td= contacto.email
        %td= image_tag '/assets/countries-flags/flag-' + contacto.pais  + '.png', :class => 'flag'
        %td= contacto.created_at.strftime("%I:%M%p %d %b %Y")
        %td= link_to 'Eliminar', contacto, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini btn-danger'

  = will_paginate @contactos

app/views/contactos/new.html.haml
= render 'form'

app/views/contactos/terminos.html.haml
%h1= page_title! "Términos y Condiciones"

%ul
  %li La promoción es válida por 1 consulta de evaluación gratis y 1 sobre de Sacián para degustar en dicha consulta en nuestros locales.

  %li Promoción válida hasta el 30 de julio de 2013.

  %li Promoción exclusiva para personas que concurran a nuestros locales.

  %li Esta promoción no es acumulable con otras promociones.

  %li Válida para los siguientes países: Perú, Bolivia y Costa Rica.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= page_title
    == <meta name="keywords" content="Sacian, Lain adelgaza" />
    == <meta name="description" content="Sacian" />
    == <meta name="googlebot" content="index,follow" />
    == <meta name="robots" content="index,follow" />
    == <meta name="Revisit-After" content="7 days" />
    == <meta name="city" content="Lima" />
    == <meta name="country" content="Peru" />
    == <meta name="state" content="Lima" />
    == <meta name="zip code" content="Lima18" />
    == <meta name="subject" content="" />
    == <meta name="author" content="Kosmyka.com" />
    == <meta name="copyright" content="&copy;Todos los derechos reservados." />
    == <meta name="geo.placename" content="Lima, Peru" />
    == <meta name="geo.region" content="PE-Lima" />
    == <meta name="author" content="humans.txt" />

    = favicon_link_tag 'favicon.png'

    - if params[:controller] == 'contactos'  && ( params[:action] == 'new' or params[:action] == 'create' )
      = stylesheet_link_tag 'application2'
    - else
      = stylesheet_link_tag 'application'
    = yield :css

    = javascript_include_tag 'application'
    = yield :scripts

    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

    /[if lt IE 9]
      %script{:src => 'http://html5shim.googlecode.com/svn/trunk/html5.js'}
    = csrf_meta_tag


  %body
    - if notice
      %p#notice= notice
    #wrapper
      %header{:role => 'banner'}
        = yield

    = render 'shared/google_analytics'

app/views/shared/_google_analytics.html.erb
<script type="text/javascript" charset="utf-8">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40291679-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>